<?php

/*return [
    'url'            => env('UC_URL', ''),
    'connect'        => env('UC_CONNECT', 'mysql'),
    'dbhost'         => env('UC_DBHOST', 'localhost'),
    'dbuser'         => env('UC_DBUSER', 'root'),
    'dbpw'           => env('UC_DBPW', 'root'),
    'dbname'         => env('UC_DBNAME', 'ucenter'),
    'dbcharset'      => env('UC_DBCHARSET', 'utf8'),
    'dbtablepre'     => env('UC_DBTABLEPRE', '`ucenter`.uc_'),
    'dbconnect'      => env('UC_DBCONNECT', '0'),
    'key'            => env('UC_KEY', '8b01LtwuRJw2NmcjA77MjFLKPQ7XmpRjTMcosGI'),
    'api'            => env('UC_API', 'http://localhost/ucenter'),
    'ip'             => env('UC_IP', '127.0.0.1'),
    'charset'        => env('UC_CHARSET', 'utf-8'),
    'appid'          => env('UC_APPID', '1'),
    'ppp'            => env('UC_PPP', '20'),
    'apifilename'    => env('UC_APIFILENAME', 'uc.php'),
    'service'        => env('UC_SERVICE', 'Binaryoung\Ucenter\Services\Api'),
];*/
return [
    'url'            => env('UC_URL', ''),
    'connect'        => env('UC_CONNECT', 'post'),
    'dbhost'         => env('UC_DBHOST', '192.168.102.200'),
    'dbuser'         => env('UC_DBUSER', 'root'),
    'dbpw'           => env('UC_DBPW', ''),
    'dbname'         => env('UC_DBNAME', 'ucenter'),
    'dbcharset'      => env('UC_DBCHARSET', 'utf8'),
    'dbtablepre'     => env('UC_DBTABLEPRE', 'uc_'),
    'dbconnect'      => env('UC_DBCONNECT', '0'),
    'key'            => env('UC_KEY', '123456'),
    'api'            => env('UC_API', 'http://www.ucenter.me'),
    'ip'             => env('UC_IP', '192.168.102.200'),
    'charset'        => env('UC_CHARSET', 'utf-8'),
    'appid'          => env('UC_APPID', '4'),
    'ppp'            => env('UC_PPP', '20'),
    'apifilename'    => env('UC_APIFILENAME', 'uc.php'),
    'service'        => env('UC_SERVICE', 'Binaryoung\Ucenter\Services\Api'),
];
